### PR TITLE
Created 'Two' Simple Themes

### PR DESCRIPTION
**Pull request by Trinxic**
I would like to add two simple versions of a theme that I created. They simply track streak/wins/losses. I followed the outline that the other themes used in this repo. I also added the screenshots to the main readme file. 

The two versions of the theme added were WLStreak - H and WLStreak - V. I am currently using this theme, so I can confirm that the configs work correctly. 

I plan to maybe add two more versions with additional stats (current/gained mmr, rank..) but this is all for now.

Thank you for your time!

### CODE REVIEW

**Comment by Arubinu** [comment]
Hello, thank you very much for this addition.
Can you change the screenshots to PNGs?

**Comment by Trinxic** [comment]
Update: I swapped the jpegs for pngs and fixed all READMEs that it affected.

**Comment by Arubinu** [comment]
Super fast, thanks. I didn't notice the Affinity files, would it be possible to delete them?
End users don't need them, and can ask you directly if needed :)

**Comment by Trinxic** [comment]
Done. I grabbed the 'arrow' images from the Actuality theme which included the Affinity files. I wasn't sure if they were necessary so I just left them in. I have tested both variations of the theme without those files present just to make sure and everything seems to work fine still!

**Comment by Arubinu** [comment]
Yes everything was good. Simple and effective theme, thanks again

**Pull request merged**
